
;占用变量 U210 - U310



;------------------------------------永久叠加属性类道具------------------------------
;31	51	1	10000	-2	0
[烈风秘药]
占用变量=U210
几率=100
单次值=1
封顶值=10
备注=攻击速度、移动速度、施法速度，永久增加<$STR(N$单次值)>%，最高<$STR(N$封顶值)>%，当前已增加<$STR(U<$STR(N$占用变量)>)>%。
失败=

[★★★★魔导秘药[剧情]]
占用变量=U211
几率=100
单次值=1
封顶值=100
备注=勇猛、生存、速度等级，永久增加<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。
失败=

[勇猛等级药水]
占用变量=U212
几率=65
单次值=1
封顶值=50
备注=成功：勇猛等级，永久增加<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。
失败=失败：勇猛等级，降低<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。

[生存等级药水]
占用变量=U213
几率=65
单次值=1
封顶值=50
备注=成功：生存等级，永久增加<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。
失败=失败：生存等级，降低<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。

[速度等级药水]
占用变量=U214
几率=65
单次值=1
封顶值=50
备注=成功：速度等级，永久增加<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。
失败=失败：速度等级，降低<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。

[★★★★★神圣穷奇之魔药[世界]]
占用变量=U215
几率=50
单次值=1
封顶值=1
备注=成功：永久增加18%对怪伤害，28%生命(仅首次生效)。
失败=服用失败，药品消失了！

[★★★力士秘药]
占用变量=U216
几率=100
单次值=5
封顶值=100
备注=勇猛等级，永久增加<$STR(N$单次值)>级，最高<$STR(N$封顶值)>级，当前已增加<$STR(U<$STR(N$占用变量)>)>级。
失败=

[虚灵丹]
占用变量=U217
几率=100
单次值=1
封顶值=50
备注=异常抗性，永久增加<$STR(N$单次值)>%，最高<$STR(N$封顶值)>%，当前已增加<$STR(U<$STR(N$占用变量)>)>%。
失败=

[★★★幽灵果实]
占用变量=U218
几率=100
单次值=1
封顶值=10
备注=对人伤害，永久增加<$STR(N$单次值)>%，最高<$STR(N$封顶值)>%，当前已增加<$STR(U<$STR(N$占用变量)>)>%。
失败=

[★★★农夫果实]
占用变量=U219
几率=100
单次值=1
封顶值=10
备注=对怪伤害，永久增加<$STR(N$单次值)>%，最高<$STR(N$封顶值)>%，当前已增加<$STR(U<$STR(N$占用变量)>)>%。
失败=

[★★★★☆疯狂药剂[本职]]
占用变量=U220
几率=100
单次值=1
封顶值=1
备注=攻击速度、移动速度、施法速度，永久增加10%
失败=

;------------------------------------给称号类道具------------------------------
;31	51	1	10001	-2


[凶神恶煞[称号]]
几率=50
称号=凶神恶煞
备注=获得了“<$STR(S$给予称号)>”称号,全基础属性+10%,杀人爆率+5%

[★★★★☆月之暗面[本职]]
几率=50
称号=月之暗面
备注=获得了“<$STR(S$给予称号)>”称号,生命偷取+5%,法力偷取+5%


[★★★★☆工程学升级[本职]]
几率=50
称号=工程学升级
备注=获得了“<$STR(S$给予称号)>”称号,异常抗性穿透+10%





;------------------------------------带CD的一次性道具------------------------------
;31	51	1	10002	-2

[疯狂果实]
占用变量=U221
冷却时间=60


[巫医之血]
占用变量=U243
记录变量=T243
图标=1300
冷却时间=1200
备注={巫医之血|250}\20分钟内你可以复活一次，并恢复50%生命。

[净化药水[特殊]]
占用变量=U245
记录变量=T245
图标=1301
持续时间=3
冷却时间=3600
备注={净化药水[特殊]|250}\移除了所有负面效果，<$STR(N$持续时间)>秒内不受任何控制。


[蛮力药剂[特殊]]
占用变量=U246
记录变量=T246
图标=1302
持续时间=60
冷却时间=3600
备注={蛮力药剂[特殊]|250}\使你伤害加成提高50%


[特效治疗药膏[特殊]]
占用变量=U247
冷却时间=3600


[魔血药水[特殊]]
占用变量=U248
冷却时间=3600


[有限无敌药水[特殊]]
占用变量=U249
记录变量=T249
图标=1303
持续时间=3
冷却时间=3600
备注={有限无敌药水[特殊]|250}\使你免疫任何伤害


[隐形药水[特殊]]
占用变量=U250
记录变量=T250
图标=1304
持续时间=300
冷却时间=3600
备注={隐形药水[特殊]|250}\使怪物无法发现你




;------------------------------------一次性给物品道具------------------------------
;31	51	1	10003	-2


[赐福福袋]
标识=银币
数量=1:10000


[苦难福袋]
标识=银币
数量=10000:100000

;------------------------------------持续BUFF类道具------------------------------
;31	51	1	10004	-2
[疯狂炸弹]
占用变量=U222
记录变量=T222
图标=1305
持续时间=60
最大时间=600
备注={疯狂炸弹|250}\造成所有伤害提升50%

[神圣卡牌]
占用变量=U222
记录变量=T222
图标=1306
持续时间=60
最大时间=600
备注={神圣卡牌|250}\造成所有伤害提升100%

[序列魔药]
占用变量=U223
记录变量=T223
图标=1307
持续时间=1800
最大时间=18000
备注={序列魔药|250}\全基础属性提升10%(包含召唤物)


[超级序列魔药]
占用变量=U223
记录变量=T223
图标=1307
持续时间=1800
最大时间=18000
备注={超级序列魔药|250}\全基础属性提升20%(包含召唤物)


[蝎蛇秘药]
占用变量=U224
记录变量=T224
图标=1308
持续时间=1800
最大时间=18000
备注={蝎蛇秘药|250}\造成所有伤害提升10%


[禁忌秘药]
占用变量=U225
记录变量=T225
图标=1309
持续时间=1800
最大时间=18000
备注={禁忌秘药|250}\忽视防御提升10%


[★★★兽人的恐怖献祭]
占用变量=U226
记录变量=T226
图标=1310
持续时间=1800
最大时间=18000
备注={★★★兽人的恐怖献祭|250}\致命一击几率提高10%


[★★★毁灭之轮]
占用变量=U227
记录变量=T227
图标=1311
持续时间=1800
最大时间=18000
备注={★★★毁灭之轮|250}\对怪造成所有伤害提高30%


[★★★赛米拉的变态面目]
占用变量=U228
记录变量=T228
图标=1312
持续时间=1800
最大时间=18000
备注={★★★赛米拉的变态面目|250}\对人造成所有伤害提高30%




[初级石化合剂]
占用变量=U229
记录变量=T229
图标=1313
持续时间=3600
最大时间=36000
备注={初级石化合剂|250}\物理减伤增加5%

[高级石化合剂]
占用变量=U229
记录变量=T229
图标=1313
持续时间=3600
最大时间=36000
备注={高级石化合剂|250}\物理减伤增加10%

[超级石化合剂]
占用变量=U229
记录变量=T229
图标=1313
持续时间=3600
最大时间=36000
备注={超级石化合剂|250}\物理减伤增加15%

[神级石化合剂]
占用变量=U229
记录变量=T229
图标=1313
持续时间=3600
最大时间=36000
备注={神级石化合剂|250}\物理减伤增加20%


[初级泰坦合剂]
占用变量=U230
记录变量=T230
图标=1314
持续时间=3600
最大时间=36000
备注={初级泰坦合剂|250}\伤害反弹增加5%

[高级泰坦合剂]
占用变量=U230
记录变量=T230
图标=1314
持续时间=3600
最大时间=36000
备注={高级泰坦合剂|250}\伤害反弹增加10%

[超级泰坦合剂]
占用变量=U230
记录变量=T230
图标=1314
持续时间=3600
最大时间=36000
备注={超级泰坦合剂|250}\伤害反弹增加15%

[神级泰坦合剂]
占用变量=U230
记录变量=T230
图标=1314
持续时间=3600
最大时间=36000
备注={神级泰坦合剂|250}\伤害反弹增加20%



[普通法力药水]
占用变量=U231
记录变量=T231
图标=1315
持续时间=3600
最大时间=36000
备注={普通法力药水|250}\法力偷取增加5%

[高级法力药水]
占用变量=U231
记录变量=T231
图标=1315
持续时间=3600
最大时间=36000
备注={高级法力药水|250}\法力偷取增加10%

[超级法力药水]
占用变量=U231
记录变量=T231
图标=1315
持续时间=3600
最大时间=36000
备注={超级法力药水|250}\法力偷取增加15%

[特效法力药水]
占用变量=U231
记录变量=T231
图标=1315
持续时间=3600
最大时间=36000
备注={特效法力药水|250}\法力偷取增加20%


[普通幸运药水]
占用变量=U232
记录变量=T232
图标=1316
持续时间=3600
最大时间=36000
备注={普通幸运药水|250}\伤害稳定率增加5%

[高级幸运药水]
占用变量=U232
记录变量=T232
图标=1316
持续时间=3600
最大时间=36000
备注={高级幸运药水|250}\伤害稳定率增加10%

[超级幸运药水]
占用变量=U232
记录变量=T232
图标=1316
持续时间=3600
最大时间=36000
备注={超级幸运药水|250}\伤害稳定率增加15%

[强效幸运药水]
占用变量=U232
记录变量=T232
图标=1316
持续时间=3600
最大时间=36000
备注={强效幸运药水|250}\伤害稳定率增加20%


[普通奥术防护药水]
占用变量=U233
记录变量=T233
图标=1317
持续时间=3600
最大时间=36000
备注={普通奥术防护药水|250}\魔法减伤增加5%

[高级奥术防护药水]
占用变量=U233
记录变量=T233
图标=1317
持续时间=3600
最大时间=36000
备注={高级奥术防护药水|250}\魔法减伤增加10%

[超级奥术防护药水]
占用变量=U233
记录变量=T233
图标=1317
持续时间=3600
最大时间=36000
备注={超级奥术防护药水|250}\魔法减伤增加15%

[强效奥术防护药水]
占用变量=U233
记录变量=T233
图标=1317
持续时间=3600
最大时间=36000
备注={强效奥术防护药水|250}\魔法减伤增加20%


[初级巨魔之血药水]
占用变量=U234
记录变量=T234
图标=1318
持续时间=3600
最大时间=36000
备注={初级巨魔之血药水|250}\生命偷取增加5%

[高级巨魔之血药水]
占用变量=U234
记录变量=T234
图标=1318
持续时间=3600
最大时间=36000
备注={高级巨魔之血药水|250}\生命偷取增加10%

[超级巨魔之血药水]
占用变量=U234
记录变量=T234
图标=1318
持续时间=3600
最大时间=36000
备注={超级巨魔之血药水|250}\生命偷取增加15%

[特效巨魔之血药水]
占用变量=U234
记录变量=T234
图标=1318
持续时间=3600
最大时间=36000
备注={特效巨魔之血药水|250}\生命偷取增加20%


[屠魔药剂[普通]]
占用变量=U235
记录变量=T235
图标=1319
持续时间=3600
最大时间=36000
备注={屠魔药剂[普通]|250}\对怪伤害增加5%

[屠魔药剂[高级]]
占用变量=U235
记录变量=T235
图标=1319
持续时间=3600
最大时间=36000
备注={屠魔药剂[高级]|250}\对怪伤害增加10%

[屠魔药剂[超级]]
占用变量=U235
记录变量=T235
图标=1319
持续时间=3600
最大时间=36000
备注={屠魔药剂[超级]|250}\对怪伤害增加15%

[屠魔药剂[特效]]
占用变量=U235
记录变量=T235
图标=1319
持续时间=3600
最大时间=36000
备注={屠魔药剂[特效]|250}\对怪伤害增加20%

[屠魔药剂[神]]
占用变量=U235
记录变量=T235
图标=1319
持续时间=3600
最大时间=36000
备注={屠魔药剂[神]|250}\对怪伤害增加25%


[初级力量药剂]
占用变量=U236
记录变量=T236
图标=1320
持续时间=3600
最大时间=36000
备注={初级力量药剂|250}\提高勇猛等级5级

[高级力量药剂]
占用变量=U236
记录变量=T236
图标=1320
持续时间=3600
最大时间=36000
备注={高级力量药剂|250}\提高勇猛等级10级

[超级力量药剂]
占用变量=U236
记录变量=T236
图标=1320
持续时间=3600
最大时间=36000
备注={超级力量药剂|250}\提高勇猛等级15级

[强效力量药剂]
占用变量=U236
记录变量=T236
图标=1320
持续时间=3600
最大时间=36000
备注={强效力量药剂|250}\提高勇猛等级20级

[神级力量药剂]
占用变量=U236
记录变量=T236
图标=1320
持续时间=3600
最大时间=36000
备注={神级力量药剂|250}\提高勇猛等级25级


[初级智力药剂]
占用变量=U237
记录变量=T237
图标=1321
持续时间=3600
最大时间=36000
备注={初级智力药剂|250}\提高生存等级5级

[高级智力药剂]
占用变量=U237
记录变量=T237
图标=1321
持续时间=3600
最大时间=36000
备注={高级智力药剂|250}\提高生存等级10级

[超级智力药剂]
占用变量=U237
记录变量=T237
图标=1321
持续时间=3600
最大时间=36000
备注={超级智力药剂|250}\提高生存等级15级

[强效智力药剂]
占用变量=U237
记录变量=T237
图标=1321
持续时间=3600
最大时间=36000
备注={强效智力药剂|250}\提高生存等级20级

[神级智力药剂]
占用变量=U237
记录变量=T237
图标=1321
持续时间=3600
最大时间=36000
备注={神级智力药剂|250}\提高生存等级25级


[初级敏捷药剂]
占用变量=U238
记录变量=T238
图标=1322
持续时间=3600
最大时间=36000
备注={初级敏捷药剂|250}\提高速度等级5级

[高级敏捷药剂]
占用变量=U238
记录变量=T238
图标=1322
持续时间=3600
最大时间=36000
备注={高级敏捷药剂|250}\提高速度等级10级

[超级敏捷药剂]
占用变量=U238
记录变量=T238
图标=1322
持续时间=3600
最大时间=36000
备注={超级敏捷药剂|250}\提高速度等级15级

[强效敏捷药剂]
占用变量=U238
记录变量=T238
图标=1322
持续时间=3600
最大时间=36000
备注={强效敏捷药剂|250}\提高速度等级20级

[神级敏捷药剂]
占用变量=U238
记录变量=T238
图标=1322
持续时间=3600
最大时间=36000
备注={神级敏捷药剂|250}\提高速度等级25级



[滋补药剂]
占用变量=U239
记录变量=T239
图标=1323
持续时间=3600
最大时间=36000
备注={滋补药剂|250}\每秒5恢复5%生命和法力

[自由行动药剂]
占用变量=U240
记录变量=T240
图标=1324
持续时间=3600
最大时间=36000
备注={自由行动药剂|250}\异常抗性增加50%

[神圣防护药水]
占用变量=U241
记录变量=T241
图标=1325
持续时间=3600
最大时间=36000
备注={神圣防护药水|250}\致命一击防御增加50%

[古神的祝福]
占用变量=U242
记录变量=T242
图标=1326
持续时间=3600
最大时间=36000
备注={古神的祝福|250}\杀怪爆率增加25%



[兽·序列魔药]
占用变量=U252
记录变量=T252
图标=1504
持续时间=3600
最大时间=36000
备注={兽·序列魔药|250}\召唤物全基础属性提升30%

;------------------------------------独立道具------------------------------
;31	51	1	10005	-2

[★★★鸟人的秘密]
占用变量=U244
封顶值=3

[★★★探视之眼[特殊]]
占用变量=U251
记录变量=T251
图标=1327
持续时间=180
冷却时间=360
触发间隔=10
消耗银币=5000
备注={★★★探视之眼[特殊]|250}\探视中...






[★★★恶魔授予的称号]
称号1=绝对恶魔
称号2=大恶魔
称号3=恶魔将军
称号4=恶魔奴仆