

[星火世界]
占用变量=J3

[猎魔世界]
占用变量=J4

[信仰世界]
占用变量=J5

[苦行世界]
占用变量=J6






; --------------------------------------------星火世界-------------------------------------
[星火世界1]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=3000

[星火世界2]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=3000

[星火世界3]
抽取怪物=4-6
进入收费=免费
怪物难度=100
爆率提升=3000

[星火世界4]
抽取怪物=4-6
进入收费=200银币
怪物难度=150
爆率提升=5000

[星火世界5]
抽取怪物=4-6
进入收费=400银币
怪物难度=150
爆率提升=8000

[星火世界6]
抽取怪物=7-9
进入收费=600银币
怪物难度=200
爆率提升=10000

[星火世界7]
抽取怪物=7-9
进入收费=800银币
怪物难度=200
爆率提升=12000

[星火世界8]
抽取怪物=10
进入收费=1000银币
怪物难度=300
爆率提升=14000

[星火世界9]
抽取怪物=10
进入收费=1200银币
怪物难度=350
爆率提升=16000

[星火世界10]
抽取怪物=10
进入收费=1400银币
怪物难度=400
爆率提升=20000

; --------------------------------------------猎魔世界-------------------------------------


[猎魔世界1]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[猎魔世界2]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[猎魔世界3]
抽取怪物=4-6
进入收费=免费
怪物难度=100
爆率提升=1500

[猎魔世界4]
抽取怪物=4-6
进入收费=400银币
怪物难度=150
爆率提升=2000

[猎魔世界5]
抽取怪物=4-6
进入收费=600银币
怪物难度=150
爆率提升=2500

[猎魔世界6]
抽取怪物=7-9
进入收费=800银币
怪物难度=200
爆率提升=3000

[猎魔世界7]
抽取怪物=7-9
进入收费=1500银币
怪物难度=200
爆率提升=3500

[猎魔世界8]
抽取怪物=10
进入收费=3000银币
怪物难度=250
爆率提升=4000

[猎魔世界9]
抽取怪物=10
进入收费=6000银币
怪物难度=350
爆率提升=4500

[猎魔世界10]
抽取怪物=10
进入收费=12000银币
怪物难度=400
爆率提升=5000

; --------------------------------------------信仰世界-------------------------------------

[信仰世界1]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[信仰世界2]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[信仰世界3]
抽取怪物=4-6
进入收费=免费
怪物难度=150
爆率提升=1500

[信仰世界4]
抽取怪物=4-6
进入收费=1000银币
怪物难度=150
爆率提升=2000

[信仰世界5]
抽取怪物=4-6
进入收费=1500银币
怪物难度=200
爆率提升=2500

[信仰世界6]
抽取怪物=7-9
进入收费=2000银币
怪物难度=250
爆率提升=3000

[信仰世界7]
抽取怪物=7-9
进入收费=2500银币
怪物难度=250
爆率提升=3500

[信仰世界8]
抽取怪物=10
进入收费=5000银币
怪物难度=300
爆率提升=4000

[信仰世界9]
抽取怪物=10
进入收费=10000银币
怪物难度=350
爆率提升=4500

[信仰世界10]
抽取怪物=10
进入收费=20000银币
怪物难度=400
爆率提升=5000
; --------------------------------------------苦行世界-------------------------------------

[苦行世界1]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[苦行世界2]
抽取怪物=1-3
进入收费=免费
怪物难度=100
爆率提升=1500

[苦行世界3]
抽取怪物=4-6
进入收费=免费
怪物难度=100
爆率提升=1500

[苦行世界4]
抽取怪物=4-6
进入收费=1500银币
怪物难度=150
爆率提升=2000

[苦行世界5]
抽取怪物=4-6
进入收费=2000银币
怪物难度=200
爆率提升=2500

[苦行世界6]
抽取怪物=7-9
进入收费=2500银币
怪物难度=250
爆率提升=3000

[苦行世界7]
抽取怪物=7-9
进入收费=5000银币
怪物难度=250
爆率提升=3500

[苦行世界8]
抽取怪物=10
进入收费=10000银币
怪物难度=300
爆率提升=4000

[苦行世界9]
抽取怪物=10
进入收费=20000银币
怪物难度=350
爆率提升=4500

[苦行世界10]
抽取怪物=10
进入收费=40000银币
怪物难度=400
爆率提升=5000