;---------------------------物品展示坐标------------------------


[物品展示坐标1]
坐标=14:26

[物品展示坐标2]
坐标=194:-37

[物品展示坐标3]
坐标=14:-34

[物品展示坐标4]
坐标=194:-98

[物品展示坐标5]
坐标=14:-95

[物品展示坐标6]
坐标=194:-159

[物品展示坐标7]
坐标=14:-156

[物品展示坐标8]
坐标=194:-220

[物品展示坐标9]
坐标=14:-217

[物品展示坐标10]
坐标=194:-281

;---------------------------综合功能页------------------------
[贡献商城1]
物品=1枚幸运币
价格=2

[贡献商城2]
物品=装备重铸石
价格=2

[贡献商城3]
物品=永久回城石
价格=150

[贡献商城4]
物品=永久随机石
价格=150

[贡献商城5]
物品=仓库扩充卷轴
价格=1

[贡献商城6]
物品=背包扩充卷轴
价格=1

[贡献商城7]
物品=转变种族证明
价格=30

[贡献商城8]
物品=黑暗空间石
价格=150

[贡献商城9]
物品=星火空间石
价格=200

[贡献商城10]
物品=猎魔空间石
价格=250

[贡献商城11]
物品=信仰空间石
价格=300

[贡献商城12]
物品=苦行空间石
价格=350

[贡献商城13]
物品=星火魔域加时卡
价格=20

[贡献商城14]
物品=猎魔魔域加时卡
价格=40

[贡献商城15]
物品=信仰魔域加时卡
价格=60

[贡献商城16]
物品=苦行魔域加时卡
价格=80

[贡献商城17]
物品=古神的祝福
价格=15

[贡献商城18]
物品=滋补药剂
价格=5

[贡献商城19]
物品=强效幸运药水
价格=15

[贡献商城20]
物品=屠魔药剂[高级]
价格=15

[贡献商城21]
物品=神级力量药剂
价格=15

[贡献商城22]
物品=神级智力药剂
价格=15

[贡献商城23]
物品=神级敏捷药剂
价格=15

[贡献商城24]
物品=高级石化合剂
价格=15

[贡献商城25]
物品=高级泰坦合剂
价格=15

[贡献商城26]
物品=疯狂果实
价格=10

[贡献商城27]
物品=超级序列魔药
价格=15

[贡献商城28]
物品=兽·序列魔药
价格=30

[贡献商城29]
物品=致命鬼爪
价格=15

[贡献商城30]
物品=魔幻毒菇
价格=15

[贡献商城31]
物品=战斗之心
价格=15

[贡献商城32]
物品=斗转罗盘
价格=15

[贡献商城33]
物品=坚硬龟壳
价格=10

[贡献商城34]
物品=太极之源
价格=10

[贡献商城34]
物品=辟邪佛手
价格=15

[贡献商城35]
物品=护体铜镜
价格=15

[贡献商城36]
物品=先手之石
价格=50

[贡献商城37]
物品=魔化狼牙
价格=50

[贡献商城38]
物品=碎冰之石
价格=50

[贡献商城39]
物品=暗夜魔蝠
价格=50

[贡献商城40]
物品=高级巨魔之血药水
价格=100

[贡献商城41]
物品=超级巨魔之血药水
价格=150

[贡献商城42]
物品=特效巨魔之血药水
价格=200
