[拆石锤]
1孔保留几率=50
2孔保留几率=30
3孔保留几率=20

[开孔钻]
1孔几率=10
2孔几率=5
3孔几率=2






;宝石填空说明
;对应数值X=
;当填空为0时代表此数值没有属性
;当填空大于0时代表固定属性
;当填空 X:X时代表随机属性



[索取之手]
镶嵌位置=头盔
镶嵌等级=不限
对应TEXT行数=644
对应数值1=1:3
对应数值2=1:3


[诡秘神格]
镶嵌位置=头盔
镶嵌等级=不限
对应TEXT行数=645
对应数值1=1:3
对应数值2=10:30


[唤灵之叶]
镶嵌位置=头盔
镶嵌等级=不限
对应TEXT行数=646
对应数值1=1:3
对应数值2=30:100


[血色灵芝]
镶嵌位置=头盔
镶嵌等级=不限
对应TEXT行数=647
对应数值1=1:3
对应数值2=200:1000


[蓝灵之羽]
镶嵌位置=头盔
镶嵌等级=不限
对应TEXT行数=648
对应数值1=1:3
对应数值2=200:1000


[致命鬼爪]
镶嵌位置=项链
镶嵌等级=不限
对应TEXT行数=649
对应数值1=1:3
对应数值2=2:6


[协调沙漏]
镶嵌位置=项链
镶嵌等级=不限
对应TEXT行数=650
对应数值1=1:3
对应数值2=30:100


[燃烧雪茄]
镶嵌位置=项链
镶嵌等级=不限
对应TEXT行数=651
对应数值1=1:3
对应数值2=10:40


[魔幻毒菇]
镶嵌位置=项链
镶嵌等级=不限
对应TEXT行数=652
对应数值1=1:3
对应数值2=10:40


[斗转罗盘]
镶嵌位置=项链
镶嵌等级=不限
对应TEXT行数=653
对应数值1=1:3
对应数值2=10:40


[战斗之心]
镶嵌位置=手镯
镶嵌等级=不限
对应TEXT行数=654
对应数值1=1:3
对应数值2=10:40


[不明组织]
镶嵌位置=手镯
镶嵌等级=不限
对应TEXT行数=655
对应数值1=1:3
对应数值2=10:40


[提线魔偶]
镶嵌位置=手镯
镶嵌等级=不限
对应TEXT行数=656
对应数值1=1:3
对应数值2=10:40


[泣血玫瑰]
镶嵌位置=手镯
镶嵌等级=不限
对应TEXT行数=657
对应数值1=1:2
对应数值2=10:100


[幻羽之蝶]
镶嵌位置=手镯
镶嵌等级=不限
对应TEXT行数=658
对应数值1=1:2
对应数值2=10:100


[猩红之眼]
镶嵌位置=戒指
镶嵌等级=不限
对应TEXT行数=659
对应数值1=1:2
对应数值2=100:1000


[天山雪莲]
镶嵌位置=戒指
镶嵌等级=不限
对应TEXT行数=660
对应数值1=1:2
对应数值2=100:1000


[魔蛛毒液]
镶嵌位置=戒指
镶嵌等级=不限
对应TEXT行数=661
对应数值1=1:2
对应数值2=100:1000


[惊恐头骨]
镶嵌位置=戒指
镶嵌等级=不限
对应TEXT行数=662
对应数值1=1:2
对应数值2=100:1000


[震慑魔眼]
镶嵌位置=戒指
镶嵌等级=不限
对应TEXT行数=663
对应数值1=1:2
对应数值2=100:1000


[坚硬龟壳]
镶嵌位置=腰带
镶嵌等级=不限
对应TEXT行数=664
对应数值1=1:3
对应数值2=10:40


[太极之源]
镶嵌位置=腰带
镶嵌等级=不限
对应TEXT行数=665
对应数值1=1:3
对应数值2=10:40


[辟邪佛手]
镶嵌位置=腰带
镶嵌等级=不限
对应TEXT行数=666
对应数值1=1:3
对应数值2=20:100


[护体铜镜]
镶嵌位置=腰带
镶嵌等级=不限
对应TEXT行数=667
对应数值1=1:3
对应数值2=20:100


[贪婪之颅]
镶嵌位置=腰带
镶嵌等级=不限
对应TEXT行数=668
对应数值1=1:3
对应数值2=1:3


[轻身之羽]
镶嵌位置=鞋子
镶嵌等级=不限
对应TEXT行数=669
对应数值1=1:2
对应数值2=30:150


[寒月血葵]
镶嵌位置=鞋子
镶嵌等级=不限
对应TEXT行数=670
对应数值1=1:3
对应数值2=10:40


[紫魔符石]
镶嵌位置=鞋子
镶嵌等级=不限
对应TEXT行数=671
对应数值1=1:3
对应数值2=10:40


[缚魔之束]
镶嵌位置=鞋子
镶嵌等级=不限
对应TEXT行数=672
对应数值1=1:3
对应数值2=50:300


[污浊之月]
镶嵌位置=鞋子
镶嵌等级=不限
对应TEXT行数=673
对应数值1=1:3
对应数值2=50:300


[魔化狼牙]
镶嵌位置=武器
镶嵌等级=不限
对应TEXT行数=674
对应数值1=1:2
对应数值2=30:150


[先手之石]
镶嵌位置=武器
镶嵌等级=不限
对应TEXT行数=675
对应数值1=1:2
对应数值2=30:150


[碎冰之石]
镶嵌位置=武器
镶嵌等级=不限
对应TEXT行数=676
对应数值1=2:5
对应数值2=60:300


[暗夜魔蝠]
镶嵌位置=武器
镶嵌等级=不限
对应TEXT行数=677
对应数值1=2:5
对应数值2=60:300


[幻魔之眼]
镶嵌位置=武器
镶嵌等级=不限
对应TEXT行数=678
对应数值1=1:5
对应数值2=2:10


[神圣之书]
镶嵌位置=衣服
镶嵌等级=不限
对应TEXT行数=679
对应数值1=1:3
对应数值2=0


[守护之轮]
镶嵌位置=衣服
镶嵌等级=不限
对应TEXT行数=680
对应数值1=1:5
对应数值2=60:300


[警醒之铃]
镶嵌位置=衣服
镶嵌等级=不限
对应TEXT行数=681
对应数值1=1:5
对应数值2=60:300


[天使护佑]
镶嵌位置=衣服
镶嵌等级=不限
对应TEXT行数=682
对应数值1=1:5
对应数值2=60:300


[不法之徒]
镶嵌位置=衣服
镶嵌等级=不限
对应TEXT行数=683
对应数值1=1:5
对应数值2=60:300


[守护之火]
镶嵌位置=副手
镶嵌等级=不限
对应TEXT行数=684
对应数值1=1:5
对应数值2=60:300


[庇护之火]
镶嵌位置=副手
镶嵌等级=不限
对应TEXT行数=685
对应数值1=1:5
对应数值2=60:300


[无尽怒火]
镶嵌位置=副手
镶嵌等级=不限
对应TEXT行数=686
对应数值1=1:5
对应数值2=60:300


[神圣之火]
镶嵌位置=副手
镶嵌等级=不限
对应TEXT行数=687
对应数值1=1:5
对应数值2=1:5


[诡秘之火]
镶嵌位置=副手
镶嵌等级=不限
对应TEXT行数=688
对应数值1=1:5
对应数值2=1:5


[异抗宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=689
对应数值1=1:2
对应数值2=0


[异穿宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=690
对应数值1=1:2
对应数值2=0


[攻击宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=691
对应数值1=5:30
对应数值2=0


[道术宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=692
对应数值1=5:30
对应数值2=0


[魔法宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=693
对应数值1=5:30
对应数值2=0


[防御宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=694
对应数值1=5:30
对应数值2=0


[魔御宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=695
对应数值1=5:30
对应数值2=0


[生命宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=696
对应数值1=100:1000
对应数值2=0


[法力宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=697
对应数值1=100:1000
对应数值2=0


[恢复宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=698
对应数值1=20:150
对应数值2=20:150


[自然宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=699
对应数值1=30:200
对应数值2=0


[亲和宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=700
对应数值1=15:150
对应数值2=0


[守护宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=701
对应数值1=500:5000
对应数值2=0


[火焰宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=702
对应数值1=30:100
对应数值2=0


[冰冷宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=703
对应数值1=30:100
对应数值2=0


[毒素宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=704
对应数值1=30:100
对应数值2=0


[闪电宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=705
对应数值1=30:100
对应数值2=0


[火抗宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=706
对应数值1=15:50
对应数值2=0


[冰抗宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=707
对应数值1=15:50
对应数值2=0


[毒抗宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=708
对应数值1=15:50
对应数值2=0


[电抗宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=709
对应数值1=15:50
对应数值2=0


[反弹宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=710
对应数值1=10:60
对应数值2=0


[吸血宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=711
对应数值1=15:50
对应数值2=0


[吸蓝宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=712
对应数值1=15:50
对应数值2=0


[祝福宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=713
对应数值1=1:5
对应数值2=0


[勇猛宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=714
对应数值1=1:3
对应数值2=0


[速度宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=715
对应数值1=1:3
对应数值2=0


[生存宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=716
对应数值1=1:3
对应数值2=0


[除魔宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=717
对应数值1=10:30
对应数值2=0


[杀手宝石]
镶嵌位置=不限
镶嵌等级=不限
对应TEXT行数=718
对应数值1=10:30
对应数值2=0
