;·---------超级人类
[农民]
勇猛等级=1:5
生存等级=1:5
速度等级=1:5
洗练需要金币=3
洗炼需要幸运币=1
洗炼需要重铸石=2
类型=超级

[步兵]
勇猛等级=2:6
生存等级=2:6
速度等级=2:6
洗练需要金币=5
洗炼需要幸运币=2
洗炼需要重铸石=8
类型=超级

[矮人火枪手]
勇猛等级=4:8
生存等级=4:8
速度等级=4:8
洗练需要金币=8
洗炼需要幸运币=3
洗炼需要重铸石=4
类型=超级

[女巫]
勇猛等级=6:10
生存等级=6:10
速度等级=6:10
洗练需要金币=12
洗炼需要幸运币=4
洗炼需要重铸石=6
类型=超级

[牧师]
勇猛等级=8:12
生存等级=8:12
速度等级=8:12
洗练需要金币=15
洗炼需要幸运币=5
洗炼需要重铸石=8
类型=超级

[骑兵]
勇猛等级=10:15
生存等级=10:15
速度等级=10:15
洗练需要金币=18
洗炼需要幸运币=6
洗炼需要重铸石=10
类型=超级

;·---------超级兽族
[骷髅战士]
勇猛等级=1:5
生存等级=1:5
速度等级=1:5
洗练需要金币=3
洗炼需要幸运币=1
洗炼需要重铸石=2
类型=超级

[骷髅将军]
勇猛等级=2:6
生存等级=2:6
速度等级=2:6
洗练需要金币=5
洗炼需要幸运币=2
洗炼需要重铸石=8
类型=超级

[亡灵骑士]
勇猛等级=4:8
生存等级=4:8
速度等级=4:8
洗练需要金币=8
洗炼需要幸运币=3
洗炼需要重铸石=4
类型=超级

[骷髅魔法师]
勇猛等级=6:10
生存等级=6:10
速度等级=6:10
洗练需要金币=12
洗炼需要幸运币=4
洗炼需要重铸石=6
类型=超级

[亡灵巫师]
勇猛等级=8:12
生存等级=8:12
速度等级=8:12
洗练需要金币=15
洗炼需要幸运币=5
洗炼需要重铸石=8
类型=超级

[女妖]
勇猛等级=10:15
生存等级=10:15
速度等级=10:15
洗练需要金币=18
洗炼需要幸运币=6
洗炼需要重铸石=10
类型=超级

;·---------超级精灵
[半精灵]
勇猛等级=1:5
生存等级=1:5
速度等级=1:5
洗练需要金币=3
洗炼需要幸运币=1
洗炼需要重铸石=2
类型=超级

[精灵]
勇猛等级=2:6
生存等级=2:6
速度等级=2:6
洗练需要金币=5
洗炼需要幸运币=2
洗炼需要重铸石=8
类型=超级

[黑精灵]
勇猛等级=4:8
生存等级=4:8
速度等级=4:8
洗练需要金币=8
洗炼需要幸运币=3
洗炼需要重铸石=4
类型=超级

[暗夜精灵]
勇猛等级=6:10
生存等级=6:10
速度等级=6:10
洗练需要金币=12
洗炼需要幸运币=4
洗炼需要重铸石=6
类型=超级

[血精灵]
勇猛等级=8:12
生存等级=8:12
速度等级=8:12
洗练需要金币=15
洗炼需要幸运币=5
洗炼需要重铸石=8
类型=超级

[光之精灵]
勇猛等级=10:15
生存等级=10:15
速度等级=10:15
洗练需要金币=18
洗炼需要幸运币=6
洗炼需要重铸石=10
类型=超级

;·---------英雄
[剑圣]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[死亡骑士]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[恶魔猎手]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[大魔法师]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[熊猫酒仙]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[山丘之王]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[巫妖]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[牛头人酋长]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[暗影猎手]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[守望者]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄


[圣骑士]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[荒野游侠]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[驯兽师]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[先知]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[娜迦海妖]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[血魔法师]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[地精修补匠]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[丛林守护者]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[火焰领主]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[恐惧魔王]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[深渊领主]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[月之祭司]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[炼金术士]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

[地穴领主]
勇猛等级=5:30
生存等级=5:30
速度等级=5:30
洗练需要金币=50
洗炼需要幸运币=8
洗炼需要重铸石=15
类型=英雄

·---------特级
[创世泰坦]
勇猛等级=10:50
生存等级=10:50
速度等级=10:50
洗练需要金币=200
洗炼需要幸运币=10
洗炼需要重铸石=30
类型=特级

[邪恶古神]
勇猛等级=10:50
生存等级=10:50
速度等级=10:50
洗练需要金币=200
洗炼需要幸运币=10
洗炼需要重铸石=30
类型=特级

[和平精灵]
勇猛等级=10:50
生存等级=10:50
速度等级=10:50
洗练需要金币=200
洗炼需要幸运币=10
洗炼需要重铸石=30
类型=特级

;·---------终极卡牌
[创世神]
勇猛等级=20:80
生存等级=20:80
速度等级=20:80
洗练需要金币=500
洗炼需要幸运币=20
洗炼需要重铸石=50
类型=终极
