[5]
类型=武器
[6]
类型=武器
[10]
类型=衣服
[11]
类型=衣服
[12]
类型=副手
[15]
类型=头盔
[24]
类型=手镯
[26]
类型=手镯
[19]
类型=项链
[20]
类型=项链
[21]
类型=项链
[22]
类型=魔盒
[23]
类型=戒指
[64]
类型=腰带
[62]
类型=鞋子
[68]
类型=卡牌
[51]
类型=头饰
[30]
类型=护符
[63]
类型=宝石
[65]
类型=印记
[28]
类型=披风
[66]
类型=时装

;副手=盾牌
;头饰=面巾
;护符=勋章
;披风=马牌
;宝石=宝石
;印记=战鼓