[神格坐标1]
坐标=20:-46

[神格坐标2]
坐标=83:-62

[神格坐标3]
坐标=146:-78

[神格坐标4]
坐标=209:-94

[神格坐标5]
坐标=272:-110

[神格坐标6]
坐标=335:-126

[神格坐标7]
坐标=398:-142

[神格坐标8]
坐标=461:-158


[神格坐标9]
坐标=20:-116

[神格坐标10]
坐标=83:-132

[神格坐标11]
坐标=146:-148

[神格坐标12]
坐标=209:-164

[神格坐标13]
坐标=272:-180

[神格坐标14]
坐标=335:-196

[神格坐标15]
坐标=398:-212

[神格坐标16]
坐标=461:-228

;---------------------------分类按钮坐标------------------------

[分类坐标1]
按钮坐标X=26
按钮坐标Y=42


[分类坐标2]
按钮坐标X=105
按钮坐标Y=26


[分类坐标3]
按钮坐标X=184
按钮坐标Y=10


[分类坐标4]
按钮坐标X=263
按钮坐标Y=-6


[分类坐标5]
按钮坐标X=342
按钮坐标Y=-22


[分类坐标6]
按钮坐标X=421
按钮坐标Y=-38




[分类1]
分类=进攻

[分类2]
分类=守卫

[分类3]
分类=召唤

[分类4]
分类=特殊


;---------------------------每转对应转生点上限------------------------

[转生0]
天赋点=0

[转生1]
天赋点=30

[转生2]
天赋点=50

[转生3]
天赋点=80

[转生4]
天赋点=120

[转生5]
天赋点=150

[转生6]
天赋点=200

[转生7]
天赋点=400

[转生8]
天赋点=600

[转生9]
天赋点=800

[转生10]
天赋点=1000

[转生11]
天赋点=1100

[转生12]
天赋点=1200

[转生13]
天赋点=1300

[转生14]
天赋点=1400

[转生15]
天赋点=1500

[转生16]
天赋点=1600

[转生17]
天赋点=1700

[转生18]
天赋点=1800

[转生19]
天赋点=1900

[转生20]
天赋点=2000



---------------------------------------进攻类----------------------------------------
[进攻1]
词条名字=攻击上限固定值
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1510
TEXT行数=8

[进攻2]
词条名字=魔法上限固定值
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1513
TEXT行数=10

[进攻3]
词条名字=道术上限固定值
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1516
TEXT行数=12

[进攻4]
词条名字=攻击百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1520
TEXT行数=17

[进攻5]
词条名字=魔法百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1523
TEXT行数=18

[进攻6]
词条名字=道术百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1526
TEXT行数=19

[进攻7]
词条名字=伤害加成
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1530
TEXT行数=23

[进攻8]
词条名字=致命一击伤害
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1533
TEXT行数=29

[进攻9]
词条名字=火焰伤害
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1536
TEXT行数=50

[进攻10]
词条名字=冰冷伤害
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1540
TEXT行数=51

[进攻11]
词条名字=毒素伤害
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1543
TEXT行数=52

[进攻12]
词条名字=闪电伤害
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1546
TEXT行数=53

[进攻13]
词条名字=火焰伤害百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1550
TEXT行数=622

[进攻14]
词条名字=冰冷伤害百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1553
TEXT行数=623

[进攻15]
词条名字=毒素伤害百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1556
TEXT行数=624

[进攻16]
词条名字=闪电伤害百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1560
TEXT行数=625

[进攻17]
词条名字=攻击时有10%几率附加%伤害
消耗点数=5
每级增加点数=2
封顶等级=50
图片编号=1563
TEXT行数=71
---------------------------------------守卫类----------------------------------------
[守卫1]
词条名字=最大防御
消耗点数=1
每级增加点数=5
封顶等级=200
图片编号=1566
TEXT行数=4

[守卫2]
词条名字=最大魔御
消耗点数=1
每级增加点数=5
封顶等级=200
图片编号=1570
TEXT行数=6

[守卫3]
词条名字=物理免疫
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1573
TEXT行数=24

[守卫4]
词条名字=魔法免疫
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1576
TEXT行数=25

[守卫5]
词条名字=每秒恢复生命
消耗点数=1
每级增加点数=10
封顶等级=100
图片编号=1580
TEXT行数=54

[守卫6]
词条名字=每秒恢复魔法
消耗点数=1
每级增加点数=10
封顶等级=100
图片编号=1583
TEXT行数=55

[守卫7]
词条名字=防御稳定率
消耗点数=5
每级增加点数=3
封顶等级=30
图片编号=1586
TEXT行数=569

[守卫8]
词条名字=火焰抗性
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1590
TEXT行数=626

[守卫9]
词条名字=冰冷抗性
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1593
TEXT行数=627

[守卫10]
词条名字=毒素抗性
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1596
TEXT行数=628

[守卫11]
词条名字=闪电抗性
消耗点数=1
每级增加点数=10
封顶等级=200
图片编号=1600
TEXT行数=629

[守卫12]
词条名字=火焰抗性百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1603
TEXT行数=630

[守卫13]
词条名字=冰冷抗性百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1606
TEXT行数=631

[守卫14]
词条名字=毒素抗性百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1610
TEXT行数=632

[守卫15]
词条名字=闪电抗性百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1613
TEXT行数=633

[守卫16]
词条名字=致命一击防御
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1616
TEXT行数=30

[守卫17]
词条名字=受到怪物攻击降低百分比
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1620
TEXT行数=82

[守卫18]
词条名字=受到人物攻击降低百分比
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1623
TEXT行数=84
---------------------------------------召唤类----------------------------------------
[召唤1]
词条名字=召唤物对怪造成伤害提高百分比
消耗点数=5
每级增加点数=1
封顶等级=100
图片编号=1626
TEXT行数=41

[召唤2]
词条名字=召唤物对人造成伤害提高百分比
消耗点数=5
每级增加点数=1
封顶等级=100
图片编号=1630
TEXT行数=43

[召唤3]
词条名字=召唤物生命百分比
消耗点数=2
每级增加点数=1
封顶等级=50
图片编号=1633
TEXT行数=37

[召唤4]
词条名字=召唤物攻击
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1636
TEXT行数=38

[召唤5]
词条名字=召唤物防御
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1640
TEXT行数=39

[召唤6]
词条名字=召唤物攻击吸取百分比
消耗点数=5
每级增加点数=1
封顶等级=5
图片编号=1643
TEXT行数=45

[召唤7]
词条名字=召唤物全属性固定值
消耗点数=5
每级增加点数=100
封顶等级=50
图片编号=1646
TEXT行数=563

[召唤8]
词条名字=召唤物继承角色主属性百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1650
TEXT行数=565

[召唤9]
词条名字=召唤物继承角色防御百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1653
TEXT行数=566

[召唤10]
词条名字=召唤物继承角色血量百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1656
TEXT行数=567
---------------------------------------特殊类----------------------------------------
[特殊1]
词条名字=攻击速度百分比
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1660
TEXT行数=20

[特殊2]
词条名字=施法速度百分比
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1663
TEXT行数=21

[特殊3]
词条名字=魔法装备获取百分比
消耗点数=5
每级增加点数=1
封顶等级=50
图片编号=1666
TEXT行数=48

[特殊4]
词条名字=异常抗性百分比
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1670
TEXT行数=31

[特殊5]
词条名字=异常抗性穿透百分比
消耗点数=5
每级增加点数=1
封顶等级=20
图片编号=1673
TEXT行数=32

[特殊6]
词条名字=致命一击几率百分比
消耗点数=5
每级增加点数=1
封顶等级=30
图片编号=1713
TEXT行数=28
