


;占用变量 
; U63 记录初级药粉
; U64 记录中级药粉
; U65 记录高级药粉

[星火世界]
可用药材1=宁神花
可用药材2=银叶草
可用药材3=地根草
可用药材4=魔皇草
可用药材5=石南草
可用药材6=荆棘藻
可用药材7=跌打草
可用药材8=野钢花
可用药材9=墓地苔
可用药材10=皇血草
说明1=同档每阶能提炼的药粉数量不同，投入越多的药粉炼药几率将会变的不同。
说明2=投入 0.5~1点 普通药粉 50%炼药失败  50%获得初级药剂  　　　　　　　 
说明3=投入1~3点 普通药粉 70%获得1级药剂 30%获得2级药剂 　　　　　　　
说明4=投入3~5点 普通药粉 50%获得1级药剂 30%获得2级药剂 20%获得3级药剂
说明5=投入5~8点 普通药粉 35%获得1级药剂 35%获得2级药剂 30%获得3级药剂
说明6=投入10点 普通药粉 100%获得3级药剂 　　　　　　　　　　　　　
说明7=使用普通药粉炼制药剂，每份需支付500银币，不同大陆提炼的药粉品质与制药价格不同。
药粉名称=普通药粉
药粉变量=63
单次制药银币=30000
输入药粉最小值=1
输入药粉最大值=10
药剂预览1=初级石化合剂
药剂预览2=初级泰坦合剂
药剂预览3=普通法力药水
药剂预览4=普通幸运药水
药剂预览5=普通奥术防护药水
药剂预览6=屠魔药剂[普通]
药剂预览7=初级力量药剂
药剂预览8=初级智力药剂
药剂预览9=初级敏捷药剂
药剂预览10=
药剂预览11=
药剂预览12=
药剂预览13=
药剂预览14=
药剂预览15=
药剂预览16=
药剂预览17=
药剂预览18=
药剂预览19=
药剂预览20=
药剂预览21=
药剂预览22=
药剂预览23=
药剂预览24=
药剂预览25=
药剂预览26=
药剂预览27=
药剂预览28=
药剂预览29=
药剂预览30=



[猎魔世界]
可用药材1=紫莲花
可用药材2=太阳草
可用药材3=幽灵菇
可用药材4=黄金参
可用药材5=梦叶草
可用药材6=黑莲花
可用药材7=火焰花
可用药材8=
可用药材9=
可用药材10=
说明1=同档每阶能提炼的药粉数量不同，投入越多的药粉炼药几率将会变的不同。
说明2=投入 0.5~1点 普通药粉 50%炼药失败  50%获得初级药剂  　　　　　　　 
说明3=投入1~3点 普通药粉 70%获得1级药剂 30%获得2级药剂 　　　　　　　
说明4=投入3~5点 普通药粉 50%获得1级药剂 30%获得2级药剂 20%获得3级药剂
说明5=投入5~8点 普通药粉 35%获得1级药剂 35%获得2级药剂 30%获得3级药剂
说明6=投入10点 普通药粉 100%获得3级药剂 　　　　　　　　　　　　　
说明7=使用普通药粉炼制药剂，每份需支付5000银币，不同大陆提炼的药粉品质与制药价格不同。
药粉名称=中级药粉
药粉变量=64
单次制药银币=50000
输入药粉最小值=1
输入药粉最大值=10
药剂预览1=初级石化合剂
药剂预览2=初级泰坦合剂
药剂预览3=普通法力药水
药剂预览4=普通幸运药水
药剂预览5=普通奥术防护药水
药剂预览6=屠魔药剂[普通]
药剂预览7=初级力量药剂
药剂预览8=初级智力药剂
药剂预览9=初级敏捷药剂
药剂预览10=高级石化合剂
药剂预览11=高级泰坦合剂
药剂预览12=高级法力药水
药剂预览13=高级幸运药水
药剂预览14=高级奥术防护药水
药剂预览15=屠魔药剂[高级]
药剂预览16=高级力量药剂
药剂预览17=高级智力药剂
药剂预览18=高级敏捷药剂
药剂预览19=超级石化合剂
药剂预览20=超级泰坦合剂
药剂预览21=超级幸运药水
药剂预览22=超级法力药水
药剂预览23=超级奥术防护药水
药剂预览24=屠魔药剂[超级]
药剂预览25=超级力量药剂
药剂预览26=超级智力药剂
药剂预览27=超级敏捷药剂
药剂预览28=
药剂预览29=
药剂预览30=



[信仰世界]
可用药材1=卡德加的胡须
可用药材2=阿尔萨斯之泪
可用药材3=格罗姆之血
可用药材4=
可用药材5=
可用药材6=
可用药材7=
可用药材8=
可用药材9=
可用药材10=
说明1=同档每阶能提炼的药粉数量不同，投入越多的药粉炼药几率将会变的不同。
说明2=投入 0.5~1点 普通药粉 50%炼药失败  50%获得初级药剂  　　　　　　　 
说明3=投入1~3点 普通药粉 70%获得1级药剂 30%获得2级药剂 　　　　　　　
说明4=投入3~5点 普通药粉 50%获得1级药剂 30%获得2级药剂 20%获得3级药剂
说明5=投入5~8点 普通药粉 35%获得1级药剂 35%获得2级药剂 30%获得3级药剂
说明6=投入10点 普通药粉 100%获得3级药剂 　　　　　　　　　　　　　
说明7=使用普通药粉炼制药剂，每份需支付50000银币，不同大陆提炼的药粉品质与制药价格不同。
药粉名称=高级药粉
药粉变量=65
单次制药银币=100000
输入药粉最小值=1
输入药粉最大值=10
药剂预览1=初级石化合剂
药剂预览2=初级泰坦合剂
药剂预览3=普通法力药水
药剂预览4=普通幸运药水
药剂预览5=普通奥术防护药水
药剂预览6=屠魔药剂[普通]
药剂预览7=初级力量药剂
药剂预览8=初级智力药剂
药剂预览9=初级敏捷药剂
药剂预览10=高级石化合剂
药剂预览11=高级泰坦合剂
药剂预览12=高级法力药水
药剂预览13=高级幸运药水
药剂预览14=高级奥术防护药水
药剂预览15=屠魔药剂[高级]
药剂预览16=高级力量药剂
药剂预览17=高级智力药剂
药剂预览18=高级敏捷药剂
药剂预览19=超级石化合剂
药剂预览20=超级泰坦合剂
药剂预览21=超级幸运药水
药剂预览22=超级法力药水
药剂预览23=超级奥术防护药水
药剂预览24=屠魔药剂[超级]
药剂预览25=超级力量药剂
药剂预览26=超级智力药剂
药剂预览27=超级敏捷药剂
药剂预览28=
药剂预览29=
药剂预览30=








[宁神花]
药粉=1
[银叶草]
药粉=2
[地根草]
药粉=3
[魔皇草]
药粉=4
[石南草]
药粉=5
[荆棘藻]
药粉=6
[跌打草]
药粉=7
[野钢花]
药粉=8
[墓地苔]
药粉=9
[皇血草]
药粉=10
[紫莲花]
药粉=11
[太阳草]
药粉=12
[幽灵菇]
药粉=13
[黄金参]
药粉=14
[梦叶草]
药粉=15
[黑莲花]
药粉=16
[火焰花]
药粉=17
[卡德加的胡须]
药粉=18
[阿尔萨斯之泪]
药粉=19
[格罗姆之血]
药粉=20