[材料仓库坐标1行]
坐标=5:33

[材料仓库坐标2行]
坐标=5:-48

[材料仓库坐标3行]
坐标=5:-129

[材料仓库坐标4行]
坐标=5:-210

[材料仓库坐标5行]
坐标=5:-291




;占用T变量 T301 T302 T303 T304 T305 T306 T307
第一行=物品名
第二行=占用变量:变量节(每一个变量分16节)
第三行=隐藏标识(绑定or非绑定)
第四行=系统标识

99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999|99999
----------------------------------------------第一页------------------------------------------------------
----------------------------------------------第一行------------------------------------------------------
[材料仓库1]
T变量=301:1
物品=宁神花


[材料仓库2]
T变量=301:2
物品=银叶草


[材料仓库3]
T变量=301:3
物品=地根草


[材料仓库4]
T变量=301:4
物品=魔皇草


[材料仓库5]
T变量=301:5
物品=石南草


[材料仓库6]
T变量=301:6
物品=荆棘藻


[材料仓库7]
T变量=301:7
物品=跌打草


[材料仓库8]
T变量=301:8
物品=野钢花

----------------------------------------------第二行------------------------------------------------------
[材料仓库9]
T变量=301:9
物品=墓地苔


[材料仓库10]
T变量=301:10
物品=皇血草


[材料仓库11]
T变量=301:11
物品=紫莲花


[材料仓库12]
T变量=301:12
物品=太阳草


[材料仓库13]
T变量=301:13
物品=幽灵菇


[材料仓库14]
T变量=301:14
物品=黄金参


[材料仓库15]
T变量=301:15
物品=梦叶草


[材料仓库16]
T变量=301:16
物品=黑莲花

----------------------------------------------第三行------------------------------------------------------
[材料仓库17]
T变量=302:1
物品=火焰花


[材料仓库18]
T变量=302:2
物品=卡德加的胡须


[材料仓库19]
T变量=302:3
物品=阿尔萨斯之泪


[材料仓库20]
T变量=302:4
物品=格罗姆之血


[材料仓库21]
T变量=302:5
物品=魔兽徽章


[材料仓库22]
T变量=302:6
物品=英勇雕像


[材料仓库23]
T变量=302:7
物品=战争荣誉


[材料仓库24]
T变量=302:8
物品=英雄之血



----------------------------------------------第四行------------------------------------------------------
[材料仓库25]
T变量=302:9
物品=一转天使之羽

[材料仓库26]
T变量=302:10
物品=二转天使之羽


[材料仓库27]
T变量=302:11
物品=三转天使之羽


[材料仓库28]
T变量=302:12
物品=四转天使之羽


[材料仓库29]
T变量=302:13
物品=五转天使之羽


[材料仓库30]
T变量=302:14
物品=六转天使之羽


[材料仓库31]
T变量=302:15
物品=七转天使之羽


[材料仓库32]
T变量=302:16
物品=八转天使之羽




----------------------------------------------第五行------------------------------------------------------
[材料仓库33]
T变量=303:1
物品=九转天使之羽


[材料仓库34]
T变量=303:2
物品=十转天使之羽

[材料仓库35]
T变量=303:3
物品=11转天使之羽


[材料仓库36]
T变量=303:4
物品=12转天使之羽


[材料仓库37]
T变量=303:5
物品=13转天使之羽


[材料仓库38]
T变量=303:6
物品=14转天使之羽


[材料仓库39]
T变量=303:7
物品=15转天使之羽


[材料仓库40]
T变量=303:8
物品=16转天使之羽

----------------------------------------------第二页------------------------------------------------------
----------------------------------------------第一行------------------------------------------------------
[材料仓库41]
T变量=303:9
物品=17转天使之羽

[材料仓库42]
T变量=303:10
物品=18转天使之羽

[材料仓库43]
T变量=303:11
物品=19转天使之羽

[材料仓库44]
T变量=303:12
物品=20转天使之羽

[材料仓库45]
T变量=303:13
物品=灵魂宝石

[材料仓库46]
T变量=303:14
物品=魔幻宝石

[材料仓库47]
T变量=303:15
物品=白骨之魂

[材料仓库48]
T变量=303:16
物品=遗忘之魂

----------------------------------------------第二行------------------------------------------------------
[材料仓库49]
T变量=304:1
物品=惊悚之心

[材料仓库50]
T变量=304:2
物品=炽烈硫磺

[材料仓库51]
T变量=304:3
物品=索取之手

[材料仓库52]
T变量=304:4
物品=诡秘神格

[材料仓库53]
T变量=304:5
物品=唤灵之叶

[材料仓库54]
T变量=304:6
物品=血色灵芝

[材料仓库55]
T变量=304:7
物品=蓝灵之羽

[材料仓库56]
T变量=304:8
物品=致命鬼爪
----------------------------------------------第三行------------------------------------------------------

[材料仓库57]
T变量=304:9
物品=协调沙漏

[材料仓库58]
T变量=304:10
物品=燃烧雪茄

[材料仓库59]
T变量=304:11
物品=魔幻毒菇

[材料仓库60]
T变量=304:12
物品=斗转罗盘

[材料仓库61]
T变量=304:13
物品=战斗之心

[材料仓库62]
T变量=304:14
物品=不明组织

[材料仓库63]
T变量=304:15
物品=提线魔偶

[材料仓库64]
T变量=304:16
物品=泣血玫瑰
----------------------------------------------第四行------------------------------------------------------
[材料仓库65]
T变量=305:1
物品=幻羽之蝶

[材料仓库66]
T变量=305:2
物品=猩红之眼

[材料仓库67]
T变量=305:3
物品=天山雪莲

[材料仓库68]
T变量=305:4
物品=魔蛛毒液

[材料仓库69]
T变量=305:5
物品=惊恐头骨

[材料仓库70]
T变量=305:6
物品=震慑魔眼

[材料仓库71]
T变量=305:7
物品=坚硬龟壳

[材料仓库72]
T变量=305:8
物品=太极之源
----------------------------------------------第五行------------------------------------------------------

[材料仓库73]
T变量=305:9
物品=辟邪佛手

[材料仓库74]
T变量=305:10
物品=护体铜镜

[材料仓库75]
T变量=305:11
物品=贪婪之颅

[材料仓库76]
T变量=305:12
物品=轻身之羽

[材料仓库77]
T变量=305:13
物品=寒月血葵

[材料仓库78]
T变量=305:14
物品=紫魔符石

[材料仓库79]
T变量=305:15
物品=缚魔之束

[材料仓库80]
T变量=305:16
物品=污浊之月


----------------------------------------------第三页------------------------------------------------------
----------------------------------------------第一行------------------------------------------------------
[材料仓库81]
T变量=306:1
物品=魔化狼牙

[材料仓库82]
T变量=306:2
物品=先手之石

[材料仓库83]
T变量=306:3
物品=碎冰之石

[材料仓库84]
T变量=306:4
物品=暗夜魔蝠

[材料仓库85]
T变量=306:5
物品=幻魔之眼

[材料仓库86]
T变量=306:6
物品=神圣之书

[材料仓库87]
T变量=306:7
物品=守护之轮

[材料仓库88]
T变量=306:8
物品=警醒之铃

----------------------------------------------第二行------------------------------------------------------
[材料仓库89]
T变量=306:9
物品=天使护佑

[材料仓库90]
T变量=306:10
物品=不法之徒

[材料仓库91]
T变量=306:11
物品=守护之火

[材料仓库92]
T变量=306:12
物品=庇护之火

[材料仓库93]
T变量=306:13
物品=无尽怒火

[材料仓库94]
T变量=306:14
物品=神圣之火

[材料仓库95]
T变量=306:15
物品=诡秘之火

[材料仓库96]
T变量=306:16
物品=异抗宝石
----------------------------------------------第三行------------------------------------------------------

[材料仓库97]
T变量=307:1
物品=异穿宝石

[材料仓库98]
T变量=307:2
物品=攻击宝石

[材料仓库99]
T变量=307:3
物品=道术宝石

[材料仓库100]
T变量=307:4
物品=魔法宝石

[材料仓库101]
T变量=307:5
物品=防御宝石

[材料仓库102]
T变量=307:6
物品=魔御宝石

[材料仓库103]
T变量=307:7
物品=生命宝石

[材料仓库104]
T变量=307:8
物品=法力宝石
----------------------------------------------第四行------------------------------------------------------
[材料仓库105]
T变量=307:9
物品=恢复宝石

[材料仓库106]
T变量=307:10
物品=自然宝石

[材料仓库107]
T变量=307:11
物品=亲和宝石

[材料仓库108]
T变量=307:12
物品=守护宝石

[材料仓库109]
T变量=307:13
物品=火焰宝石

[材料仓库110]
T变量=307:14
物品=冰冷宝石

[材料仓库111]
T变量=307:15
物品=毒素宝石

[材料仓库112]
T变量=307:16
物品=闪电宝石
----------------------------------------------第五行------------------------------------------------------

[材料仓库113]
T变量=308:1
物品=火抗宝石

[材料仓库114]
T变量=308:2
物品=冰抗宝石

[材料仓库115]
T变量=308:3
物品=毒抗宝石

[材料仓库116]
T变量=308:4
物品=电抗宝石

[材料仓库117]
T变量=308:5
物品=吸血宝石

[材料仓库118]
T变量=308:6
物品=吸蓝宝石

[材料仓库119]
T变量=308:7
物品=祝福宝石

[材料仓库120]
T变量=308:8
物品=勇猛宝石
----------------------------------------------第四页------------------------------------------------------
----------------------------------------------第一行------------------------------------------------------
[材料仓库121]
T变量=308:9
物品=速度宝石

[材料仓库122]
T变量=308:10
物品=生存宝石

[材料仓库123]
T变量=308:11
物品=除魔宝石

[材料仓库124]
T变量=308:12
物品=杀手宝石
[材料仓库125]				
T变量=308:13
物品=反弹宝石		
