


[坐标1]
坐标=20:40

[坐标2]
坐标=112:24

[坐标3]
坐标=204:8

[坐标4]
坐标=20:60

[坐标5]
坐标=112:44

[坐标6]
坐标=204:28

[坐标7]
坐标=20:80


;占用变量 U481 U482 U483 U484 U485 U486
[属性1]
名字=勇猛专精
图标=80
备注=每级增加勇猛等级：1级
变量=481
银币等级乘法基数=30
银币递增加法基数=2000
需要材料=遗忘之魂
材料等级乘法基数=1
材料递增加法基数=5

[属性2]
名字=生存专精
图标=83
备注=每级增加生存等级：1级
变量=482
银币等级乘法基数=30
银币递增加法基数=2000
需要材料=魔幻宝石
材料等级乘法基数=1
材料递增加法基数=5

[属性3]
名字=速度专精
图标=86
备注=每级增加速度等级：1级
变量=483
银币等级乘法基数=30
银币递增加法基数=2000
需要材料=白骨之魂
材料等级乘法基数=1
材料递增加法基数=5

[属性4]
名字=对怪伤害专精
图标=90
备注=每级增加对怪伤害：1%
变量=484
银币等级乘法基数=50
银币递增加法基数=4000
需要材料=灵魂宝石
材料等级乘法基数=1
材料递增加法基数=5

[属性5]
名字=伤害加成专精
图标=93
备注=每级增加伤害加成：1%
变量=485
银币等级乘法基数=50
银币递增加法基数=4000
需要材料=惊悚之心
材料等级乘法基数=1
材料递增加法基数=5

[属性6]
名字=爆率专精
图标=96
备注=每级增加杀怪爆率：1%
变量=486
银币等级乘法基数=50
银币递增加法基数=4000
需要材料=炽烈硫磺
材料等级乘法基数=1
材料递增加法基数=5


[属性7]
名字=召唤物对怪伤害专精
图标=310
备注=每级增加召唤物对怪伤害：1%
变量=487
银币等级乘法基数=50
银币递增加法基数=4000
需要材料=灵魂宝石
材料等级乘法基数=1
材料递增加法基数=5