;占用SET [21] [22] [23] 记录激活标识

[星火世界]
装备评分=25000
等级要求=75
转生条件=5
材料1=恐怖手镯:1
材料2=恶轮束带:1
材料3=沙虫皮靴:1
材料4=暗夜束腰:1
材料5=束缚者魔甲:1
材料6=蛛丝战靴:1
SET变量=21
激活大陆=猎魔世界
传送点=猎魔世界:437:493

[猎魔世界]
装备评分=80000
等级要求=135
转生条件=10
材料1=警惕宝珠:1
材料2=射手护腕:1
材料3=逃亡披风:1
材料4=精铜手套:1
材料5=魔珠手镯:1
材料6=亡者之镯:1
SET变量=22
激活大陆=信仰世界
传送点=信仰世界:500:523

[信仰世界]
装备评分=180000
等级要求=150
转生条件=15
材料1=魔偶超级图腾:1
材料2=异变之靴:1
材料3=徘徊号角:1
材料4=月色守护之链:1
材料5=山丘虫巢:1
材料6=蛛王血祭:1
SET变量=23
激活大陆=苦行世界
传送点=苦行世界:551:323
