﻿﻿﻿﻿





[成就坐标1]
坐标=76:-41

[成就坐标2]
坐标=76:-58

[成就坐标3]
坐标=76:-75

[成就坐标4]
坐标=76:-92

[成就坐标5]
坐标=76:-109

[成就坐标6]
坐标=76:-126


;---------------------------分类按钮坐标------------------------

[分类坐标1]
按钮坐标X=26
按钮坐标Y=42


[分类坐标2]
按钮坐标X=105
按钮坐标Y=26


[分类坐标3]
按钮坐标X=184
按钮坐标Y=10


[分类坐标4]
按钮坐标X=263
按钮坐标Y=-6


[分类坐标5]
按钮坐标X=342
按钮坐标Y=-22


[分类坐标6]
按钮坐标X=421
按钮坐标Y=-38




[分类1]
分类=怪物

[分类2]
分类=成长

[分类3]
分类=PVP

[分类4]
分类=赞助

[分类5]
分类=时长

[分类6]
分类=其他



;占用 U1 记录成就点
;占用个人标识 [500] 起步 到 [600] 结束
;所有成就变量为U变量
;占用 U151 U152 U153 U154 U155 U156 U157 U158 U159 U160
;占用 U161 U162 U163 U164 U165 U166 U167 U168 U169 U170
;占用 U171 U172 U173 U174 U175 U176 U177 U178 U179 U180
;占用 U181 U182 U183 U184 U185 U186 U187 U188 U189 U190
---------------------------------------杀怪类----------------------------------------




;-----------------------第一页-------------------
[怪物1]
成就名字=小怪杀手Ⅰ
成就说明=杀死普通怪物到达1000只
成就奖励=10
成就变量=151
成就目标=1000
成就标识=500

[怪物2]
成就名字=小怪杀手Ⅱ
成就说明=杀死普通怪物到达5000只
成就奖励=30
成就变量=151
成就目标=5000
成就标识=501

[怪物3]
成就名字=小怪杀手Ⅲ
成就说明=杀死普通怪物到达50000只
成就奖励=50
成就变量=151
成就目标=50000
成就标识=502

[怪物4]
成就名字=首领杀手Ⅰ
成就说明=杀死首领怪物到达300只
成就奖励=30
成就变量=152
成就目标=300
成就标识=503

[怪物5]
成就名字=首领杀手Ⅱ
成就说明=杀死首领怪物到达1000只
成就奖励=100
成就变量=152
成就目标=1000
成就标识=504

[怪物6]
成就名字=首领杀手Ⅲ
成就说明=杀死首领怪物到达3000只
成就奖励=300
成就变量=152
成就目标=3000
成就标识=505

;-----------------------第二页-------------------
[怪物7]
成就名字=超级仲裁者Ⅰ
成就说明=杀死超级BOSS到达150只
成就奖励=30
成就变量=153
成就目标=150
成就标识=506

[怪物8]
成就名字=超级仲裁者Ⅱ
成就说明=杀死超级BOSS到达300只
成就奖励=60
成就变量=153
成就目标=300
成就标识=507

[怪物9]
成就名字=超级仲裁者Ⅲ
成就说明=杀死超级BOSS到达600只
成就奖励=120
成就变量=153
成就目标=600
成就标识=508

[怪物10]
成就名字=剧情推进者Ⅰ
成就说明=杀死剧情BOSS达到50只
成就奖励=30
成就变量=154
成就目标=50
成就标识=509

[怪物11]
成就名字=剧情推进者Ⅱ
成就说明=杀死剧情BOSS达到150只
成就奖励=60
成就变量=154
成就目标=150
成就标识=510

[怪物12]
成就名字=剧情推进者Ⅲ
成就说明=杀死剧情BOSS达到300只
成就奖励=100
成就变量=154
成就目标=300
成就标识=511

;-----------------------第三页-------------------
[怪物13]
成就名字=世界知名人物Ⅰ
成就说明=杀死世界boss到达10只
成就奖励=30
成就变量=155
成就目标=10
成就标识=512

[怪物14]
成就名字=世界知名人物Ⅱ
成就说明=杀死世界boss到达50只
成就奖励=60
成就变量=155
成就目标=50
成就标识=513

[怪物15]
成就名字=世界知名人物Ⅲ
成就说明=杀死世界boss到达100只
成就奖励=100
成就变量=155
成就目标=100
成就标识=514

[怪物16]
成就名字=小怪杀手Ⅳ
成就说明=杀死普通怪物到达100000只
成就奖励=100
成就变量=151
成就目标=100000
成就标识=588

[怪物17]
成就名字=小怪杀手Ⅴ
成就说明=杀死普通怪物到达200000只
成就奖励=200
成就变量=151
成就目标=200000
成就标识=589

[怪物18]
成就名字=首领杀手Ⅳ
成就说明=杀死首领怪物到达5000只
成就奖励=500
成就变量=152
成就目标=5000
成就标识=590

[怪物19]
成就名字=超级仲裁者Ⅳ
成就说明=杀死超级BOSS到达1000只
成就奖励=200
成就变量=153
成就目标=1000
成就标识=591

[怪物20]
成就名字=剧情推进者Ⅳ
成就说明=杀死剧情BOSS达到500只
成就奖励=150
成就变量=154
成就目标=500
成就标识=592

[怪物21]
成就名字=世界知名人物Ⅳ
成就说明=杀死世界boss到达200只
成就奖励=150
成就变量=155
成就目标=200
成就标识=593




;---------------------------------------装备类----------------------------------------

;-----------------------第一页-------------------
[成长1]
成就名字=初级重铸师
成就说明=重铸装备次数达到100次
成就奖励=10
成就变量=156
成就目标=100
成就标识=515

[成长2]
成就名字=学员重铸师
成就说明=重铸装备次数达到500次
成就奖励=20
成就变量=156
成就目标=500
成就标识=516

[成长3]
成就名字=大师重铸师
成就说明=重铸装备次数达到3000次
成就奖励=30
成就变量=156
成就目标=3000
成就标识=517

[成长4]
成就名字=宗师重铸师
成就说明=重铸装备次数达到5000次
成就奖励=50
成就变量=156
成就目标=5000
成就标识=518

[成长5]
成就名字=见习药剂师
成就说明=成功炼药次数达到100次
成就奖励=30
成就变量=157
成就目标=100
成就标识=519

[成长6]
成就名字=学员药剂师
成就说明=成功炼药次数达到500次
成就奖励=50
成就变量=157
成就目标=500
成就标识=520

;-----------------------第二页-------------------
[成长7]
成就名字=大师药剂师
成就说明=成功炼药次数达到3000次
成就奖励=100
成就变量=157
成就目标=3000
成就标识=521

[成长8]
成就名字=宗师药剂师
成就说明=成功炼药次数达到5000次
成就奖励=150
成就变量=157
成就目标=5000
成就标识=522


[成长9]
成就名字=初级学者
成就说明=成功使用查询次数达到100次
成就奖励=50
成就变量=158
成就目标=100
成就标识=523

[成长10]
成就名字=中级学者
成就说明=成功使用查询次数达到300次
成就奖励=75
成就变量=158
成就目标=300
成就标识=524

[成长11]
成就名字=高级学者
成就说明=成功使用查询次数达到600次
成就奖励=100
成就变量=158
成就目标=600
成就标识=525

[成长12]
成就名字=顶级学者
成就说明=成功使用查询次数达到1500次
成就奖励=200
成就变量=158
成就目标=1500
成就标识=526

;-----------------------第三页-------------------


[成长13]
成就名字=全职业者Ⅰ
成就说明=转变职业次数达到10次
成就奖励=10
成就变量=159
成就目标=10
成就标识=527

[成长14]
成就名字=全职业者Ⅱ
成就说明=转变职业次数达到30次
成就奖励=30
成就变量=159
成就目标=30
成就标识=528

[成长15]
成就名字=全职业者Ⅲ
成就说明=转变职业次数达到50次
成就奖励=50
成就变量=159
成就目标=50
成就标识=529

[成长16]
成就名字=全职精通大师
成就说明=转变职业次数达到100次
成就奖励=100
成就变量=159
成就目标=100
成就标识=530

[成长17]
成就名字=勇猛大师
成就说明=属性专精处升级勇猛等级到100级
成就奖励=30
成就变量=481
成就目标=100
成就标识=531

[成长18]
成就名字=生存大师
成就说明=属性专精处升级生存等级到100级
成就奖励=30
成就变量=482
成就目标=100
成就标识=532

[成长19]
成就名字=速度大师
成就说明=属性专精处升级速度等级到100级
成就奖励=30
成就变量=483
成就目标=100
成就标识=533

[成长20]
成就名字=狩猎大师
成就说明=属性专精处升级对怪伤害到100级
成就奖励=30
成就变量=484
成就目标=100
成就标识=534

[成长21]
成就名字=格斗大师
成就说明=属性专精处升级伤害加成到100级
成就奖励=30
成就变量=485
成就目标=100
成就标识=535

[成长22]
成就名字=寻宝大师
成就说明=属性专精处升级爆率专精到100级
成就奖励=30
成就变量=486
成就目标=100
成就标识=536

[成长23]
成就名字=全能大师
成就说明=属性专精处升级所有专精到100级
成就奖励=150
成就变量=160
成就目标=1
成就标识=537


[成长24]
成就名字=职业之王
成就说明=本职业技能全部达到100重
成就奖励=300
成就变量=167
成就目标=1
成就标识=538

---------------------------------------PVP类----------------------------------------




;-----------------------第一页-------------------
[PVP1]
成就名字=以暴制暴
成就说明=被卸掉狂暴10次
成就奖励=50
成就变量=168
成就目标=10
成就标识=539

[PVP2]
成就名字=暴无可暴
成就说明=被卸掉狂暴100次
成就奖励=150
成就变量=168
成就目标=100
成就标识=540


[PVP3]
成就名字=狂暴之徒
成就说明=卸掉敌人狂暴10次
成就奖励=50
成就变量=169
成就目标=10
成就标识=541

[PVP4]
成就名字=黑暗暴君
成就说明=卸掉敌人狂暴100次
成就奖励=150
成就变量=169
成就目标=100
成就标识=542


[PVP5]
成就名字=猎杀者Ⅰ
成就说明=累计杀死等级相差较小的敌人10次
成就奖励=10
成就变量=170
成就目标=10
成就标识=543


[PVP6]
成就名字=猎杀者Ⅱ
成就说明=累计杀死等级相差较小的敌人30次
成就奖励=45
成就变量=170
成就目标=30
成就标识=544

;-----------------------第二页-------------------
[PVP7]
成就名字=猎杀者Ⅱ
成就说明=累计杀死等级相差较小的敌人100次
成就奖励=160
成就变量=170
成就目标=100
成就标识=545


[PVP8]
成就名字=首席仲裁者
成就说明=首次获得全职业排行榜第一
成就奖励=100
成就变量=171
成就目标=1
成就标识=546


[PVP9]
成就名字=职业佼佼者
成就说明=首次获得任意职业排行榜第一
成就奖励=50
成就变量=172
成就目标=1
成就标识=547


[PVP10]
成就名字=捐献大使
成就说明=首次进行沙巴克捐献
成就奖励=30
成就变量=173
成就目标=1
成就标识=548


[PVP11]
成就名字=插旗为营
成就说明=首次创建行会
成就奖励=15
成就变量=174
成就目标=1
成就标识=549


[PVP12]
成就名字=拉帮结派
成就说明=首次加入行会
成就奖励=30
成就变量=175
成就目标=1
成就标识=550

;-----------------------第三页-------------------
[PVP13]
成就名字=沙巴克之魂
成就说明=首次成为沙巴克成员
成就奖励=100
成就变量=176
成就目标=1
成就标识=551

[PVP14]
成就名字=沙巴克之王
成就说明=首次成为沙巴克老大
成就奖励=300
成就变量=177
成就目标=1
成就标识=552






---------------------------------------充值类----------------------------------------
;-----------------------第一页-------------------
[赞助1]
成就名字=从不白嫖
成就说明=购买任意赞助即可获得
成就奖励=50
成就变量=178
成就目标=1
成就标识=553

[赞助2]
成就名字=只玩顶赞
成就说明=充值或打充值成功达到顶级赞助
成就奖励=150
成就变量=179
成就目标=1
成就标识=554


[赞助3]
成就名字=贡献者Ⅰ
成就说明=累计使用贡献150点
成就奖励=50
成就变量=180
成就目标=150
成就标识=555

[赞助4]
成就名字=贡献者Ⅱ
成就说明=累计使用贡献300点
成就奖励=75
成就变量=180
成就目标=300
成就标识=556

[赞助5]
成就名字=贡献者Ⅲ
成就说明=累计使用贡献750点
成就奖励=100
成就变量=180
成就目标=750
成就标识=557

[赞助6]
成就名字=贡献者Ⅳ
成就说明=累计使用贡献1500点
成就奖励=120
成就变量=180
成就目标=1500
成就标识=558

[赞助7]
成就名字=贡献者Ⅴ
成就说明=累计使用贡献3000点
成就奖励=150
成就变量=180
成就目标=3000
成就标识=559

[赞助8]
成就名字=贡献之王
成就说明=累计使用贡献5000点
成就奖励=200
成就变量=180
成就目标=5000
成就标识=560


[赞助9]
成就名字=财大气粗
成就说明=充值或打充值达到1000
成就奖励=100
成就变量=181
成就目标=1000
成就标识=561
额外奖励=获得“财大气粗”标识，所有技能魔次+1(与白手起家成就生效其一)

[赞助10]
成就名字=富甲天下
成就说明=充值或打充值达到2000
成就奖励=300
成就变量=181
成就目标=2000
成就标识=562
额外奖励=获得“富甲天下”标识，所有技能魔次+2(与身家丰厚成就生效其一)

[赞助11]
成就名字=家财万贯
成就说明=充值或打充值达到3000
成就奖励=1000
成就变量=181
成就目标=3000
成就标识=563
额外奖励=获得“家财万贯”标识，所有技能魔次+3(与腰缠万贯成就生效其一)






---------------------------------------时长类----------------------------------------
[时长1]
成就名字=冒险新星
成就说明=在线时长达到1440分钟
成就奖励=25
成就变量=182
成就目标=1440
成就标识=564

[时长2]
成就名字=冒险旅者
成就说明=在线时长达到2880分钟
成就奖励=50
成就变量=182
成就目标=2880
成就标识=565

[时长3]
成就名字=冒险精英
成就说明=在线时长达到7200分钟
成就奖励=100
成就变量=182
成就目标=7200
成就标识=566

[时长4]
成就名字=冒险英雄
成就说明=在线时长达到14400分钟
成就奖励=150
成就变量=182
成就目标=14400
成就标识=567

[时长5]
成就名字=冒险领袖
成就说明=在线时长达到43200分钟
成就奖励=200
成就变量=182
成就目标=43200
成就标识=568

[时长6]
成就名字=初级咸鱼
成就说明=挂机打怪时长达到1440分钟
成就奖励=25
成就变量=183
成就目标=1440
成就标识=569

[时长7]
成就名字=中级咸鱼
成就说明=挂机打怪时长达到2880分钟
成就奖励=50
成就变量=183
成就目标=2880
成就标识=570

[时长8]
成就名字=高级咸鱼
成就说明=挂机打怪时长达到7200分钟
成就奖励=100
成就变量=183
成就目标=7200
成就标识=571

[时长9]
成就名字=超级咸鱼
成就说明=挂机打怪时长达到14400分钟
成就奖励=150
成就变量=183
成就目标=14400
成就标识=572

[时长10]
成就名字=咸鱼王
成就说明=挂机打怪时长达到43200分钟
成就奖励=200
成就变量=183
成就目标=43200
成就标识=573

[时长11]
成就名字=报道，仲裁者！
成就说明=首次签到成功
成就奖励=10
成就变量=54
成就目标=1
成就标识=574

[时长12]
成就名字=见习仲裁者
成就说明=连续签到3天
成就奖励=30
成就变量=54
成就目标=3
成就标识=575

[时长13]
成就名字=正式仲裁者
成就说明=连续签到7天
成就奖励=100
成就变量=54
成就目标=7
成就标识=576

[时长14]
成就名字=骨干仲裁者
成就说明=连续签到30天
成就奖励=300
成就变量=54
成就目标=30
成就标识=577





---------------------------------------其他类----------------------------------------

[其他1]
成就名字=非常人Ⅰ
成就说明=转变种族5次
成就奖励=25
成就变量=184
成就目标=5
成就标识=578

[其他2]
成就名字=非常人Ⅱ
成就说明=转变种族10次
成就奖励=50
成就变量=184
成就目标=10
成就标识=579

[其他3]
成就名字=非常人Ⅲ
成就说明=转变种族30次
成就奖励=100
成就变量=184
成就目标=30
成就标识=580

[其他4]
成就名字=非常人Ⅳ
成就说明=转变种族50次
成就奖励=150
成就变量=184
成就目标=50
成就标识=581

[其他5]
成就名字=非常人Ⅴ
成就说明=转变种族100次
成就奖励=200
成就变量=184
成就目标=100
成就标识=582



;---------------------------------后加配置----------------------
[赞助12]
成就名字=壕无人性
成就说明=充值或打充值达到5000
成就奖励=3000
成就变量=181
成就目标=5000
成就标识=583
额外奖励=获得“壕无人性”标识，所有技能魔次+5(与富甲一方成就生效其一)



[成长24]
成就名字=白手起家
成就说明=累计获得10000金币(不计算充值获得金币)
成就奖励=100
成就变量=185
成就目标=10000
成就标识=584
额外奖励=获得“白手起家”标识，所有技能魔次+1(与财大气粗成就生效其一)

[成长25]
成就名字=身家丰厚
成就说明=累计获得30000金币(不计算充值获得金币)
成就奖励=300
成就变量=185
成就目标=30000
成就标识=585
额外奖励=获得“身家丰厚”标识，所有技能魔次+2(与富甲天下成就生效其一)

[成长26]
成就名字=腰缠万贯
成就说明=累计获得100000金币(不计算充值获得金币)
成就奖励=1000
成就变量=185
成就目标=100000
成就标识=586
额外奖励=获得“腰缠万贯”标识，所有技能魔次+3(与家财万贯成就生效其一)

[成长27]
成就名字=富甲一方
成就说明=累计获得300000金币(不计算充值获得金币)
成就奖励=3000
成就变量=185
成就目标=300000
成就标识=587
额外奖励=获得“富甲一方”标识，所有技能魔次+5(与壕无人性成就生效其一)
---------------------------------------成就奖励配置----------------------------------------

[150点奖励]
奖励=称号:无畏黑铁
标识=716


[650点奖励]
奖励=称号:倔强青铜
标识=717


[1150点奖励]
奖励=称号:秩序白银
标识=718


[1650点奖励]
奖励=称号:荣耀黄金
标识=719


[2150点奖励]
奖励=称号:尊贵铂金
标识=720


[2650点奖励]
奖励=称号:永恒钻石
标识=721


[3150点奖励]
奖励=称号:至尊星耀
标识=722


[3650点奖励]
奖励=称号:超凡大师
标识=723


[4150点奖励]
奖励=称号:最强王者
标识=724

[4650点奖励]
奖励=称号:传奇霸主
标识=725

[5150点奖励]
奖励=称号:神话传说
标识=726

[5650点奖励]
奖励=称号:宇宙主宰
标识=727




