


;===================================狂信徒===================================

[残暴打击]
图标=1336


[鲁莽挥击]
图标=1338

[英勇冲锋]
图标=1342

[诸神黄昏]
图标=1344













;===================================惩罚者===================================
[致残打击]
图标=1352
[战争践踏]
图标=1354
[跳斩]
图标=1358
[伤口愈合]
图标=1360

;===================================光明骑士===================================
[神圣之怒]
图标=1370
[神圣护盾]
图标=1372
[神圣化身]
图标=1376

;===================================暗杀者===================================
[潜行]
图标=1384
[毁伤]
图标=1386
[刺骨]
图标=1388
[杀戮盛宴]
图标=1392

;===================================游荡者===================================
[出血]
图标=1398
[暗影步]
图标=1400

;===================================雷罚使徒===================================
[瞬移术]
图标=1416
[雷电领域]
图标=1418
[能量爆发]
图标=1424

;===================================熔岩法师===================================
[炎爆术]
图标=1432
[龙息术]
图标=1434
[气定神闲]
图标=1438

;===================================极寒术士===================================
[冰霜新星]
图标=1446
[冰霜屏障]
图标=1450

;===================================地狱尊者===================================
[死灵狂暴]
图标=1468

;===================================苦修士===================================

;===================================德鲁伊===================================

[台风]
图标=1498
