


;===================================狂信徒===================================


[残暴打击]
耗蓝基数=20
[鲁莽挥击]
耗蓝基数=20
[英勇冲锋]
耗蓝基数=50










;===================================惩罚者===================================

[致残打击]
耗蓝基数=20
[战争践踏]
耗蓝基数=20
[跳斩]
耗蓝基数=50


;===================================光明骑士===================================

[神圣之怒]
耗蓝基数=100


;===================================暗杀者===================================

[毁伤]
耗蓝基数=20
[刺骨]
耗蓝基数=20
[杀戮盛宴]
耗蓝基数=100

;===================================游荡者===================================
[出血]
耗蓝基数=20


;===================================雷罚使徒===================================
[闪电飞弹]
耗蓝基数=2
[闪电脉冲]
耗蓝基数=20
[闪电风暴]
耗蓝基数=10

;===================================熔岩法师===================================
[火球术]
耗蓝基数=2
[火墙术]
耗蓝基数=20
[炎爆术]
耗蓝基数=50
[龙息术]
耗蓝基数=50
[火焰之雨]
耗蓝基数=10

;===================================极寒术士===================================
[寒冰箭]
耗蓝基数=2
[暴风雪]
耗蓝基数=10
[冰霜新星]
耗蓝基数=50



;===================================地狱尊者===================================
[暗影箭]
耗蓝基数=2
[腐蚀术]
耗蓝基数=10
[奴役怪物]
耗蓝基数=50

;===================================苦修士===================================
[惩击]
耗蓝基数=2
[神圣震击]
耗蓝基数=10
[暗言术]
耗蓝基数=20

;===================================德鲁伊===================================

[旋风]
耗蓝基数=2
[飓风]
耗蓝基数=10
[台风]
耗蓝基数=50
