


;===================================狂信徒===================================


[诸神黄昏]
耗蓝基数=100









;===================================惩罚者===================================

[伤口愈合]
耗蓝基数=100

;===================================光明骑士===================================

[神圣化身]
耗蓝基数=100

;===================================暗杀者===================================
[潜行]
耗蓝基数=100


;===================================游荡者===================================

[暗影步]
耗蓝基数=50
[元素陷阱]
耗蓝基数=50

;===================================雷罚使徒===================================

[能量爆发]
耗蓝基数=100
;===================================熔岩法师===================================

[气定神闲]
耗蓝基数=100
;===================================极寒术士===================================

[冰霜屏障]
耗蓝基数=100
[召唤水元素]
耗蓝基数=100



;===================================地狱尊者===================================

[召唤骷髅]
耗蓝基数=50
[召唤恶魔]
耗蓝基数=100
[死灵狂暴]
耗蓝基数=100
;===================================苦修士===================================

[治愈术]
耗蓝基数=20
[群体治愈术]
耗蓝基数=40

[暗影形态]
耗蓝基数=50
[召唤侍从]
耗蓝基数=100
;===================================德鲁伊===================================

[回春术]
耗蓝基数=20
[召唤饿狼]
耗蓝基数=50

[野性之魂]
耗蓝基数=50
